### ISSUE TITLE
fix: auth controllers tests fail and stop circleci deployment

### ISSUE THREAD

**Issue by karansapolia** [pesto-students/batch-10-tripen#116]
## Type of Issue
- [x] Bug
- [ ] Feature request
- [ ] Tests addition request
- [ ] Refactor request
- [ ] Build changes request
- [ ] CI / CD change requests
- [ ] Documentation request
- [ ] Dependency upgrade request
- [ ] Other... Please describe:

## Issue Description
Auth tests have a few issues:
1. [x]  Perform tests on test server instead of in-memory mongodb server.
         - This makes tests slower.
         - Some tests like signup ( document creation ) tests cannot be performed twice with same data without deleting older entry. Consequently, subsequent tests fail.
2. [x] Tests pass only the first time around. WIth all subsequent commits, they fail ( as explained in the points above). 

**Todo**: 
1. [x] Shift tests to use mongodb-memory-server instead of a remote test server.
