### ISSUE TITLE
fix: Link User meta bar to Profile Page.

### ISSUE THREAD

**Issue by p-racoon** [pesto-students/batch-10-tripen#127]
## Type of Issue
- [x] Bug
- [ ] Feature request
- [ ] Tests addition request
- [ ] Refactor request
- [ ] Build changes request
- [ ] CI / CD change requests
- [ ] Documentation request
- [ ] Dependency upgrade request
- [ ] Other... Please describe:

## Issue Description
When a logged in user clicks on the profile button in header, he/she is not redirected to Profile Page.
